name: NodeJS with Gulp

on:
  workflow_dispatch:
    inputs:
      create_release:
        default: true
        description: 'Create Github Release'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    outputs: 
      majorMinorPatch: ${{ steps.setoutputs.outputs.majorMinorPatch }}
      semver: ${{ steps.setoutputs.outputs.semver }}
      
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build SPFx
      run: |
        npm install
        gulp bundle --ship
        gulp package-solution --ship

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: news-carousel
        path: ${{ github.workspace }}/**/*.sppkg

  release:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.ref_name == 'main' || startsWith(github.ref_name, 'release') || github.event.inputs.create_release }}
    needs: build
    steps:
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/download-artifact@v3
        with:
          name: news-carousel
    
      - name: Create GitHub release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: news-carousel
          artifacts: ${{ github.workspace }}/**/*.sppkg
          bodyFile: ".github/workflows/release-template.md"
          draft: true
          generateReleaseNotes: true
          allowUpdates: true
          replacesArtifacts: true
          prerelease: ${{ startsWith(github.ref_name, 'release') }}
          tag: ${{ needs.build.outputs.majorMinorPatch }}
          commit: ${{ github.ref_name }} 
          token: ${{ secrets.TOKEN }}
